AWSTemplateFormatVersion: 2010-09-09
Description: DNS recordset for hosting the site on Github Pages

Parameters:
  kayakLaunchZoneID:
    Type: String
    Description: The Route53 Zone ID for the kayaklaun.ch. zone.

Resources:
  kayakLaunchGithubCname:
    Type: AWS::Route53::RecordSet
    Properties: 
      HostedZoneId:
        Ref: kayakLaunchZoneID 
      Name: www.kayaklaun.ch.
      Type: CNAME
      TTL: '900'
      ResourceRecords:
      - binghamchris.github.io.